name: DevOps Recruiter Finder

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas requests openpyxl

      - name: Run scraper
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          SEARCH_ENGINE_ID: ${{ secrets.SEARCH_ENGINE_ID }}
        run: python scraper.py

      - name: Commit Excel
        run: |
          git config --global user.name "github-bot"
          git config --global user.email "bot@github.com"
          git add recruiters.xlsx
          git commit -m "Update recruiter database" || echo "No changes"
          git push
